### ISSUE TITLE
Issues with patching on Local Windows Machine

### ISSUE THREAD

**Issue by digvijayad** [symplify/vendor-patches#10]
I had a couple of issues while applying a patch on my local windows . I'll mention them here if someone else faces the same issues. If there is a better way please let me know. 

- The directory separator for windows (#4) needed to be changed using PR #9 
- The composer-patches requires the package to either be a git package or the fall back method of using `patch` command. 
    `patch` command is linux based. There are two ways to solve this. 
     1. Install the package via its git source using `compose require [package] --prefer-source`. 
         This will get the package from git rather than the dist version. 
     2. Install Patch for windows from [here.](https://gnuwin32.sourceforge.net/packages/patch.htm) and add it to your path. Note: I could not get this to work on my machine, as running patch opened a new command line but nothing happened after that. 
- I had to run composer-install to install other packages, then run `compose require [package] --prefer-source` just for that specific package, so that composer-patches will recognise it as a git package, and apply patch, or add repo directly to composer.   
- The .patch file generated `--- /dev/null`, which gave me `error: new file dist/client.js depends on old contents`. 
```
   --- /dev/null
   +++ ../dist/client.js
```
So, I updated the patched file to
```
--- ../dist/client.js
+++ ../dist/client.js
```
   based on the answer [here](https://stackoverflow.com/a/52221725/4714773) which fixed the issue for me.

**Comment by BriceFab** [comment]
+1

Same here with my Windows path:

`private const VENDOR_PACKAGE_DIRECTORY_REGEX = '#^(?<vendor_package_directory>.*?vendor\\/(\\w|\\.|\\-)+\\/(\\w|\\.|\\-)+)\\/#si';
    public function resolveVendorDirectory(SmartFileInfo $fileInfo) : string
    {
        $test = $fileInfo->getRealPath();

        dump($test);

//        $test = str_replace('\\', '/', $test);

        $match = Strings::match($test, self::VENDOR_PACKAGE_DIRECTORY_REGEX);

        dd($test, self::VENDOR_PACKAGE_DIRECTORY_REGEX, $match);
        if (!isset($match['vendor_package_directory'])) {
            throw new ShouldNotHappenException('Could not resolve vendor package directory');
        }
        return $match['vendor_package_directory'];
    }`
