### ISSUE TITLE
Generates unusable .patch file

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [symplify/vendor-patches#16]
Hello there, 

I got an issue while i was creating a little patch. I used quite sometimes so i just don't know whats wrong. 

1. I created this patch file: 

[store-shopware-com-topdatacompareproducts-src-resources-app-storefront-dist-storefront-js-topdata-compare-products-js.patch](https://github.com/symplify/vendor-patches/files/13650293/store-shopware-com-topdatacompareproducts-src-resources-app-storefront-dist-storefront-js-topdata-compare-products-js.patch)

2. since Shopware installs plugins in a custom directory inside vendor i had to adjust the composer.json this way (as you can see i have done that before with another patch for the same package): 

![Bildschirmfoto 2023-12-12 um 16 59 19](https://github.com/symplify/vendor-patches/assets/57937533/0af5a557-8c56-46a7-aea1-01e0351f0eba)

3. when I try to run composer install it cannot find the file to patch. Maybe someone can help me whats wrong with that path ?

![Bildschirmfoto 2023-12-12 um 16 56 16](https://github.com/symplify/vendor-patches/assets/57937533/2df2694d-956c-4e7a-a6b2-0e8ce4cec18f)

**Comment by TomasVotruba** [comment]
Hi, this package only uses patch package as a wrapper.
Also, we only support standard vendor paths. 

For this you'll have to create a custom wrapper.

**Comment by Nico-Schaefer-2111** [comment]
hi @TomasVotruba 

Thanks for your fast response. But could you make a guess how I could solve the problem? 
Sorry but it would help me alot, since I have really no clue why it can't find the file...

**Comment by TomasVotruba** [comment]
Hi, I always use the default value here to save the pain,
so I have no idea.
