### ISSUE TITLE
Issue with directory separators

### ISSUE THREAD

**Issue by fritzmg** [symplify/vendor-patches#19]
I use Windows as my dev environment. When I execute `vendor/bin/vendor-patches generate` it creates `extra.patches` entries like this in the `composer.json`:

```json
"vendor/foobar": [
    "patches\\path-to-php.patch"
]
```

However, this will not work when deploying this to the live environment, which typically is _not_ a Windows environment 😄

Directory separators in the `composer.json` should always be a forward slash, so that it works both on Windows and Unix based environments.

**Comment by TomasVotruba** [comment]
Thanks for feedback 🙂

Could you fix it here?

https://github.com/symplify/vendor-patches/blob/main/src/PatchFileFactory.php#L26

**Comment by fritzmg** [comment]
Yes, see #20
