### ISSUE TITLE
Wrong patch generation (dev/null)

### ISSUE THREAD

**Issue by AlejandroAkbal** [symplify/vendor-patches#23]
This is an example patch generated with vendor-patches

spatie-laravel-medialibrary-src-conversions-jobs-performconversionsjob-php.patch
```diff
--- /dev/null
+++ ../src/Conversions/Jobs/PerformConversionsJob.php
@@ -27,6 +27,9 @@

     public function handle(FileManipulator $fileManipulator): bool
     {
+        // Raise memory limit
+        ini_set('memory_limit', '1024M');
+
         $fileManipulator->performConversions(
             $this->conversions,
             $this->media,
```

As you can see, I think it's creating a new file? Instead of modifying the existing one

Other users have found the same issue
https://github.com/cweagans/composer-patches/discussions/567#discussioncomment-9191921

**Comment by TomasVotruba** [comment]
This bug has to be fixed in the linked package. We're only wrapping the tool here.
