### ISSUE TITLE
Is it possible to patch js assets?

### ISSUE THREAD

**Issue by nevez** [symplify/vendor-patches#24]
Hello,

I'm trying to patch a .js file (one line of code), but I get this:

> [OK] No new patches were added

Is there a way to patch vendor assets?

Thanks for any help

**Comment by TomasVotruba** [comment]
Hey, it should be supported.

This would be method to debug: https://github.com/symplify/vendor-patches/blob/585e7504e9f32f03186c2a39a3d530a95851616c/src/Finder/OldToNewFilesFinder.php#L30-L43

**Comment by nevez** [comment]
The Finder iterator was not returning files because... I modified a file in a "vendor" folder of a different project. Insert facepalm.

Sorry, and thanks for answering.
