### ISSUE TITLE
Incorrect directory separators under windows.

### ISSUE THREAD

**Issue by BARNZ** [symplify/vendor-patches#4]
This is a great package, but had to make a few small tweaks to get it working under my windows machine.

There were 2 places in the code that are checking a regex against a filepath, however on windows my filepaths have backslashes instead of forward slashes causing the regex to fail to match.

For example in `PathResolver.php` getRealPath returns on my machine:
`C:\path\to\www\app\vendor\package\file.php`
instead of the expected
`C:/path/to/www/app/vendor/package/file.php`

to workaround this issue I simply changed any calls to `$fileInfo->getRealPath()` to `str_replace('\\', '/', $fileInfo->getRealPath())` in the following files:
* PathResolver.php
* PatchDiffer.php

I can submit a pull request with this fix if you'd like?

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting :+1: 

> I can submit a pull request with this fix if you'd like?

That would be best :)

**Comment by tomasfejfar** [comment]
JFYI https://symfony.com/doc/current/components/filesystem.html#path-manipulation-utilities ;) 

I actually submitted a PR to symfony regarding this (which is why I know it exists in the first place), but in the end this was a superior implementation. It also takes care about some of the edge-cases.

**Comment by kmd-technomed** [comment]
I encountered the same issue ln52 of PatchDiffer and the solution proposed by @BARNZ worked a treat there as well. 
@BARNZ can you confirm and if so can you roll the PatchDiffer alteration up into your PR please?
