### ISSUE TITLE
Incompatible with vaimo/composer-patches

### ISSUE THREAD

**Issue by michaelarnauts** [symplify/vendor-patches#7]
I'm using `vaimo/composer-patches` instead of `cweagans/composer-patches` since I only want to use my own patches, and not the ones from upstream. This isn't configurable in the library of cweagans.

However, since this package requires `cweagans/composer-patches`, it doesn't want to install.

Could you also make it compatible with `vaimo/composer-patches`, or just drop the dependency on `cweagans/composer-patches`?

**Comment by TomasVotruba** [comment]
Hi, I'm not sure it possible. 
The `cweagans/composer-patches` is a hard dependency here, as we build on it.

You can stick with `vaimo/composer-patches` or move to this one.
